# Generated by Django 5.1 on 2024-09-04 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomur', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kresler',
            new_name='Tomurcuk',
        ),
    ]
