# Generated by Django 5.1 on 2024-09-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomur', '0002_rename_kresler_tomurcuk'),
    ]

    operations = [
        migrations.AddField(
            model_name='tomurcuk',
            name='aciklama',
            field=models.TextField(default='Açıklama girilmedi'),
        ),
        migrations.AddField(
            model_name='tomurcuk',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tomurcuk',
            name='oda_adi',
            field=models.CharField(default='Belirtilmedi', max_length=30),
        ),
        migrations.AddField(
            model_name='tomurcuk',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tomurcuk',
            name='telefon',
            field=models.CharField(default='Not Provided', help_text='+90 ile başlayacak şekilde giriniz', max_length=20),
        ),
    ]
