# Generated by Django 5.1 on 2024-09-06 13:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomur', '0004_telefon_alter_tomurcuk_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tomurcuk',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
