# Generated by Django 5.1 on 2024-09-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomur', '0005_tomurcuk_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tomurcuk',
            name='email',
        ),
        migrations.AddField(
            model_name='telefon',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
