# Generated by Django 5.1 on 2024-09-07 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomur', '0007_instagrampost_alter_tomurcuk_aciklama'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstagramPost',
        ),
    ]
