# Generated by Django 5.1 on 2024-09-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomur', '0008_delete_instagrampost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='etkinlik_fotolar/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='etkinlik_videolar/')),
            ],
        ),
        migrations.CreateModel(
            name='Etkinlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255)),
                ('aciklama', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('foto', models.ManyToManyField(blank=True, to='tomur.foto')),
                ('video', models.ManyToManyField(blank=True, to='tomur.video')),
            ],
            options={
                'ordering': ['-tarih'],
            },
        ),
    ]
