# Generated by Django 5.1 on 2024-09-07 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomur', '0009_foto_video_etkinlik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etkinlik',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='etkinlik',
            name='video',
        ),
        migrations.DeleteModel(
            name='Foto',
        ),
        migrations.DeleteModel(
            name='Etkinlik',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
