# Generated by Django 5.1 on 2024-09-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomur', '0010_remove_etkinlik_foto_remove_etkinlik_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtkinlikResim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='etkinlik_resimleri/')),
            ],
        ),
        migrations.CreateModel(
            name='Etkinlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('aciklama', models.TextField()),
                ('resimler', models.ManyToManyField(blank=True, related_name='etkinlikler', to='tomur.etkinlikresim')),
            ],
        ),
    ]
