# Generated by Django 5.1 on 2024-09-07 18:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomur', '0011_etkinlikresim_etkinlik'),
    ]

    operations = [
        migrations.AddField(
            model_name='etkinlik',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etkinlikresim',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
