# Generated by Django 5.1 on 2024-09-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomur', '0012_etkinlik_created_at_alter_etkinlikresim_resim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egitim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egitim_adi', models.CharField(max_length=200, verbose_name='Eğitim Adı')),
                ('aciklama', models.TextField(verbose_name='Eğitim Açıklaması')),
            ],
        ),
    ]
