# Generated by Django 5.1 on 2024-09-08 12:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomur', '0013_egitim'),
    ]

    operations = [
        migrations.AddField(
            model_name='egitim',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
