# Generated by Django 5.1 on 2024-09-09 16:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomur', '0015_ogretmen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='egitim',
            options={'verbose_name_plural': 'Eğitimler'},
        ),
        migrations.AlterModelOptions(
            name='etkinlik',
            options={'verbose_name_plural': 'Etkinlikler'},
        ),
        migrations.AlterModelOptions(
            name='ogretmen',
            options={'verbose_name_plural': 'Öğretmenler'},
        ),
        migrations.AddField(
            model_name='ogretmen',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
